//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gama.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGamaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GamaBaseListener : IGamaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GamaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GamaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceDefault</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDefault([NotNull] GamaParser.NamespaceDefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceDefault</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDefault([NotNull] GamaParser.NamespaceDefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceRootStart</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceRootStart([NotNull] GamaParser.NamespaceRootStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceRootStart</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceRootStart([NotNull] GamaParser.NamespaceRootStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceRoot</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceRoot([NotNull] GamaParser.NamespaceRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceRoot</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceRoot([NotNull] GamaParser.NamespaceRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ImportStmt</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] GamaParser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ImportStmt</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] GamaParser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelStatement([NotNull] GamaParser.TopLevelStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelStatement([NotNull] GamaParser.TopLevelStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructLevelDelegate</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructLevelDelegate([NotNull] GamaParser.StructLevelDelegateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructLevelDelegate</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructLevelDelegate([NotNull] GamaParser.StructLevelDelegateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructLevelMethod</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructLevelMethod([NotNull] GamaParser.StructLevelMethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructLevelMethod</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructLevelMethod([NotNull] GamaParser.StructLevelMethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] GamaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] GamaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtVarDefBase([NotNull] GamaParser.StmtVarDefBaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtVarDefBase([NotNull] GamaParser.StmtVarDefBaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefFull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtVarDefFull([NotNull] GamaParser.StmtVarDefFullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefFull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtVarDefFull([NotNull] GamaParser.StmtVarDefFullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefNull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtVarDefNull([NotNull] GamaParser.StmtVarDefNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefNull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtVarDefNull([NotNull] GamaParser.StmtVarDefNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.stmtAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtAssign([NotNull] GamaParser.StmtAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.stmtAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtAssign([NotNull] GamaParser.StmtAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtIfBase([NotNull] GamaParser.StmtIfBaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtIfBase([NotNull] GamaParser.StmtIfBaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtIfElse([NotNull] GamaParser.StmtIfElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtIfElse([NotNull] GamaParser.StmtIfElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElseIf</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtIfElseIf([NotNull] GamaParser.StmtIfElseIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElseIf</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtIfElseIf([NotNull] GamaParser.StmtIfElseIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElseIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtIfElseIfElse([NotNull] GamaParser.StmtIfElseIfElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElseIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtIfElseIfElse([NotNull] GamaParser.StmtIfElseIfElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtReturnVoid</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtReturnVoid([NotNull] GamaParser.StmtReturnVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtReturnVoid</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtReturnVoid([NotNull] GamaParser.StmtReturnVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtReturnValue</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtReturnValue([NotNull] GamaParser.StmtReturnValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtReturnValue</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtReturnValue([NotNull] GamaParser.StmtReturnValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtWhileBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtWhileBase([NotNull] GamaParser.StmtWhileBaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtWhileBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtWhileBase([NotNull] GamaParser.StmtWhileBaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtDoWhile</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtDoWhile([NotNull] GamaParser.StmtDoWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtDoWhile</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtDoWhile([NotNull] GamaParser.StmtDoWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.stmtFnCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtFnCall([NotNull] GamaParser.StmtFnCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.stmtFnCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtFnCall([NotNull] GamaParser.StmtFnCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelBlock([NotNull] GamaParser.TopLevelBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelBlock([NotNull] GamaParser.TopLevelBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] GamaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] GamaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpMul</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprOpMul([NotNull] GamaParser.ExprOpMulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpMul</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprOpMul([NotNull] GamaParser.ExprOpMulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralString</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLiteralString([NotNull] GamaParser.ExprLiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralString</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLiteralString([NotNull] GamaParser.ExprLiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpAdd</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprOpAdd([NotNull] GamaParser.ExprOpAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpAdd</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprOpAdd([NotNull] GamaParser.ExprOpAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpComp</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprOpComp([NotNull] GamaParser.ExprOpCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpComp</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprOpComp([NotNull] GamaParser.ExprOpCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprParenthesis</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprParenthesis([NotNull] GamaParser.ExprParenthesisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprParenthesis</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprParenthesis([NotNull] GamaParser.ExprParenthesisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprPointerLoad</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprPointerLoad([NotNull] GamaParser.ExprPointerLoadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprPointerLoad</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprPointerLoad([NotNull] GamaParser.ExprPointerLoadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprCall</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprCall([NotNull] GamaParser.ExprCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprCall</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprCall([NotNull] GamaParser.ExprCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralInteger</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLiteralInteger([NotNull] GamaParser.ExprLiteralIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralInteger</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLiteralInteger([NotNull] GamaParser.ExprLiteralIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralBoolean</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLiteralBoolean([NotNull] GamaParser.ExprLiteralBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralBoolean</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLiteralBoolean([NotNull] GamaParser.ExprLiteralBooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralChar</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLiteralChar([NotNull] GamaParser.ExprLiteralCharContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralChar</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLiteralChar([NotNull] GamaParser.ExprLiteralCharContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprFQMB</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprFQMB([NotNull] GamaParser.ExprFQMBContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprFQMB</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprFQMB([NotNull] GamaParser.ExprFQMBContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralFloating</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprLiteralFloating([NotNull] GamaParser.ExprLiteralFloatingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralFloating</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprLiteralFloating([NotNull] GamaParser.ExprLiteralFloatingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprFQTN</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprFQTN([NotNull] GamaParser.ExprFQTNContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprFQTN</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprFQTN([NotNull] GamaParser.ExprFQTNContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprAddressOf</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAddressOf([NotNull] GamaParser.ExprAddressOfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprAddressOf</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAddressOf([NotNull] GamaParser.ExprAddressOfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpLogic</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprOpLogic([NotNull] GamaParser.ExprOpLogicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpLogic</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprOpLogic([NotNull] GamaParser.ExprOpLogicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] GamaParser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] GamaParser.ExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelUsingNamespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelUsingNamespace([NotNull] GamaParser.TopLevelUsingNamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelUsingNamespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelUsingNamespace([NotNull] GamaParser.TopLevelUsingNamespaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelDelegate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDelegate([NotNull] GamaParser.TopLevelDelegateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelDelegate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDelegate([NotNull] GamaParser.TopLevelDelegateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelExternDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelExternDef([NotNull] GamaParser.TopLevelExternDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelExternDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelExternDef([NotNull] GamaParser.TopLevelExternDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelFuncDef([NotNull] GamaParser.TopLevelFuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelFuncDef([NotNull] GamaParser.TopLevelFuncDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelStructDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelStructDef([NotNull] GamaParser.TopLevelStructDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelStructDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelStructDef([NotNull] GamaParser.TopLevelStructDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelImpl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelImpl([NotNull] GamaParser.TopLevelImplContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelImpl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelImpl([NotNull] GamaParser.TopLevelImplContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolTypePairList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolTypePairList([NotNull] GamaParser.SymbolTypePairListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolTypePairList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolTypePairList([NotNull] GamaParser.SymbolTypePairListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolTypePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolTypePair([NotNull] GamaParser.SymbolTypePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolTypePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolTypePair([NotNull] GamaParser.SymbolTypePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.ellipsis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEllipsis([NotNull] GamaParser.EllipsisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.ellipsis"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEllipsis([NotNull] GamaParser.EllipsisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.funcAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncAttr([NotNull] GamaParser.FuncAttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.funcAttr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncAttr([NotNull] GamaParser.FuncAttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolList([NotNull] GamaParser.SymbolListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolList([NotNull] GamaParser.SymbolListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opMul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpMul([NotNull] GamaParser.OpMulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opMul"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpMul([NotNull] GamaParser.OpMulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpAdd([NotNull] GamaParser.OpAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpAdd([NotNull] GamaParser.OpAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpComp([NotNull] GamaParser.OpCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpComp([NotNull] GamaParser.OpCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opLogic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLogic([NotNull] GamaParser.OpLogicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opLogic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLogic([NotNull] GamaParser.OpLogicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtnRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFqtnRoot([NotNull] GamaParser.FqtnRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtnRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFqtnRoot([NotNull] GamaParser.FqtnRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFqtn([NotNull] GamaParser.FqtnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFqtn([NotNull] GamaParser.FqtnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtnList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFqtnList([NotNull] GamaParser.FqtnListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtnList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFqtnList([NotNull] GamaParser.FqtnListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeList([NotNull] GamaParser.TypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeList([NotNull] GamaParser.TypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] GamaParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] GamaParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.ptr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPtr([NotNull] GamaParser.PtrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.ptr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPtr([NotNull] GamaParser.PtrContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
