//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gama.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GamaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IGamaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GamaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GamaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceDefault</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceDefault([NotNull] GamaParser.NamespaceDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceDefault</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceDefault([NotNull] GamaParser.NamespaceDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceRootStart</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceRootStart([NotNull] GamaParser.NamespaceRootStartContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceRootStart</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceRootStart([NotNull] GamaParser.NamespaceRootStartContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceRoot</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceRoot([NotNull] GamaParser.NamespaceRootContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceRoot</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceRoot([NotNull] GamaParser.NamespaceRootContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImportStmt</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] GamaParser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImportStmt</c>
	/// labeled alternative in <see cref="GamaParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] GamaParser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelStatement([NotNull] GamaParser.TopLevelStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelStatement([NotNull] GamaParser.TopLevelStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructLevelDelegate</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructLevelDelegate([NotNull] GamaParser.StructLevelDelegateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructLevelDelegate</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructLevelDelegate([NotNull] GamaParser.StructLevelDelegateContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructLevelMethod</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructLevelMethod([NotNull] GamaParser.StructLevelMethodContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructLevelMethod</c>
	/// labeled alternative in <see cref="GamaParser.structLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructLevelMethod([NotNull] GamaParser.StructLevelMethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GamaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GamaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtVarDefBase([NotNull] GamaParser.StmtVarDefBaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtVarDefBase([NotNull] GamaParser.StmtVarDefBaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefFull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtVarDefFull([NotNull] GamaParser.StmtVarDefFullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefFull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtVarDefFull([NotNull] GamaParser.StmtVarDefFullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtVarDefNull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtVarDefNull([NotNull] GamaParser.StmtVarDefNullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtVarDefNull</c>
	/// labeled alternative in <see cref="GamaParser.stmtVarDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtVarDefNull([NotNull] GamaParser.StmtVarDefNullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.stmtAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtAssign([NotNull] GamaParser.StmtAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.stmtAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtAssign([NotNull] GamaParser.StmtAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtIfBase([NotNull] GamaParser.StmtIfBaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtIfBase([NotNull] GamaParser.StmtIfBaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtIfElse([NotNull] GamaParser.StmtIfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtIfElse([NotNull] GamaParser.StmtIfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElseIf</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtIfElseIf([NotNull] GamaParser.StmtIfElseIfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElseIf</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtIfElseIf([NotNull] GamaParser.StmtIfElseIfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtIfElseIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtIfElseIfElse([NotNull] GamaParser.StmtIfElseIfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtIfElseIfElse</c>
	/// labeled alternative in <see cref="GamaParser.stmtIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtIfElseIfElse([NotNull] GamaParser.StmtIfElseIfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtReturnVoid</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtReturnVoid([NotNull] GamaParser.StmtReturnVoidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtReturnVoid</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtReturnVoid([NotNull] GamaParser.StmtReturnVoidContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtReturnValue</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtReturnValue([NotNull] GamaParser.StmtReturnValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtReturnValue</c>
	/// labeled alternative in <see cref="GamaParser.stmtReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtReturnValue([NotNull] GamaParser.StmtReturnValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtWhileBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtWhileBase([NotNull] GamaParser.StmtWhileBaseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtWhileBase</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtWhileBase([NotNull] GamaParser.StmtWhileBaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtDoWhile</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtDoWhile([NotNull] GamaParser.StmtDoWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtDoWhile</c>
	/// labeled alternative in <see cref="GamaParser.stmtWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtDoWhile([NotNull] GamaParser.StmtDoWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.stmtFnCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtFnCall([NotNull] GamaParser.StmtFnCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.stmtFnCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtFnCall([NotNull] GamaParser.StmtFnCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelBlock([NotNull] GamaParser.TopLevelBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelBlock([NotNull] GamaParser.TopLevelBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] GamaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] GamaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpMul</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOpMul([NotNull] GamaParser.ExprOpMulContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpMul</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOpMul([NotNull] GamaParser.ExprOpMulContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralString</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLiteralString([NotNull] GamaParser.ExprLiteralStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralString</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLiteralString([NotNull] GamaParser.ExprLiteralStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprIndex</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprIndex([NotNull] GamaParser.ExprIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprIndex</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprIndex([NotNull] GamaParser.ExprIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpAdd</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOpAdd([NotNull] GamaParser.ExprOpAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpAdd</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOpAdd([NotNull] GamaParser.ExprOpAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpComp</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOpComp([NotNull] GamaParser.ExprOpCompContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpComp</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOpComp([NotNull] GamaParser.ExprOpCompContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprParenthesis</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprParenthesis([NotNull] GamaParser.ExprParenthesisContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprParenthesis</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprParenthesis([NotNull] GamaParser.ExprParenthesisContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprPointerLoad</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprPointerLoad([NotNull] GamaParser.ExprPointerLoadContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprPointerLoad</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprPointerLoad([NotNull] GamaParser.ExprPointerLoadContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprCall</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprCall([NotNull] GamaParser.ExprCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprCall</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprCall([NotNull] GamaParser.ExprCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralInteger</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLiteralInteger([NotNull] GamaParser.ExprLiteralIntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralInteger</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLiteralInteger([NotNull] GamaParser.ExprLiteralIntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralBoolean</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLiteralBoolean([NotNull] GamaParser.ExprLiteralBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralBoolean</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLiteralBoolean([NotNull] GamaParser.ExprLiteralBooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralChar</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLiteralChar([NotNull] GamaParser.ExprLiteralCharContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralChar</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLiteralChar([NotNull] GamaParser.ExprLiteralCharContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprFQMB</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprFQMB([NotNull] GamaParser.ExprFQMBContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprFQMB</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprFQMB([NotNull] GamaParser.ExprFQMBContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprLiteralFloating</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprLiteralFloating([NotNull] GamaParser.ExprLiteralFloatingContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprLiteralFloating</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprLiteralFloating([NotNull] GamaParser.ExprLiteralFloatingContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprFQTN</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprFQTN([NotNull] GamaParser.ExprFQTNContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprFQTN</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprFQTN([NotNull] GamaParser.ExprFQTNContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprAddressOf</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAddressOf([NotNull] GamaParser.ExprAddressOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprAddressOf</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAddressOf([NotNull] GamaParser.ExprAddressOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprOpLogic</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOpLogic([NotNull] GamaParser.ExprOpLogicContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprOpLogic</c>
	/// labeled alternative in <see cref="GamaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOpLogic([NotNull] GamaParser.ExprOpLogicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] GamaParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] GamaParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelUsingNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelUsingNamespace([NotNull] GamaParser.TopLevelUsingNamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelUsingNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelUsingNamespace([NotNull] GamaParser.TopLevelUsingNamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelDelegate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelDelegate([NotNull] GamaParser.TopLevelDelegateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelDelegate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelDelegate([NotNull] GamaParser.TopLevelDelegateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelExternDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelExternDef([NotNull] GamaParser.TopLevelExternDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelExternDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelExternDef([NotNull] GamaParser.TopLevelExternDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelFuncDef([NotNull] GamaParser.TopLevelFuncDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelFuncDef([NotNull] GamaParser.TopLevelFuncDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelStructDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelStructDef([NotNull] GamaParser.TopLevelStructDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelStructDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelStructDef([NotNull] GamaParser.TopLevelStructDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.topLevelImpl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelImpl([NotNull] GamaParser.TopLevelImplContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.topLevelImpl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelImpl([NotNull] GamaParser.TopLevelImplContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolTypePairList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbolTypePairList([NotNull] GamaParser.SymbolTypePairListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolTypePairList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbolTypePairList([NotNull] GamaParser.SymbolTypePairListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolTypePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbolTypePair([NotNull] GamaParser.SymbolTypePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolTypePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbolTypePair([NotNull] GamaParser.SymbolTypePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.ellipsis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEllipsis([NotNull] GamaParser.EllipsisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.ellipsis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEllipsis([NotNull] GamaParser.EllipsisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.funcAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncAttr([NotNull] GamaParser.FuncAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.funcAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncAttr([NotNull] GamaParser.FuncAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.symbolList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbolList([NotNull] GamaParser.SymbolListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.symbolList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbolList([NotNull] GamaParser.SymbolListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opMul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpMul([NotNull] GamaParser.OpMulContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opMul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpMul([NotNull] GamaParser.OpMulContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpAdd([NotNull] GamaParser.OpAddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpAdd([NotNull] GamaParser.OpAddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpComp([NotNull] GamaParser.OpCompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpComp([NotNull] GamaParser.OpCompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.opLogic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpLogic([NotNull] GamaParser.OpLogicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.opLogic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpLogic([NotNull] GamaParser.OpLogicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtnRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFqtnRoot([NotNull] GamaParser.FqtnRootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtnRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFqtnRoot([NotNull] GamaParser.FqtnRootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFqtn([NotNull] GamaParser.FqtnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFqtn([NotNull] GamaParser.FqtnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.fqtnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFqtnList([NotNull] GamaParser.FqtnListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.fqtnList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFqtnList([NotNull] GamaParser.FqtnListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] GamaParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] GamaParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] GamaParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] GamaParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaParser.ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtr([NotNull] GamaParser.PtrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaParser.ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtr([NotNull] GamaParser.PtrContext context);
}
