//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GamaPreprocessor.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGamaPreprocessorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GamaPreprocessorBaseListener : IGamaPreprocessorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GamaPreprocessorParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GamaPreprocessorParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorIncludeStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorIncludeStmt([NotNull] GamaPreprocessorParser.PreprocessorIncludeStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorIncludeStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorIncludeStmt([NotNull] GamaPreprocessorParser.PreprocessorIncludeStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorDefineStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorDefineStmt([NotNull] GamaPreprocessorParser.PreprocessorDefineStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorDefineStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorDefineStmt([NotNull] GamaPreprocessorParser.PreprocessorDefineStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorUndefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorUndefStmt([NotNull] GamaPreprocessorParser.PreprocessorUndefStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorUndefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorUndefStmt([NotNull] GamaPreprocessorParser.PreprocessorUndefStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorIf</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorIf([NotNull] GamaPreprocessorParser.PreprocessorIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorIf</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorIf([NotNull] GamaPreprocessorParser.PreprocessorIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorIfdefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorIfdefStmt([NotNull] GamaPreprocessorParser.PreprocessorIfdefStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorIfdefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorIfdefStmt([NotNull] GamaPreprocessorParser.PreprocessorIfdefStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorIfndefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorIfndefStmt([NotNull] GamaPreprocessorParser.PreprocessorIfndefStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorIfndefStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorIfndefStmt([NotNull] GamaPreprocessorParser.PreprocessorIfndefStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorPragmaStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorPragmaStmt([NotNull] GamaPreprocessorParser.PreprocessorPragmaStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorPragmaStmt</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorPragmaStmt([NotNull] GamaPreprocessorParser.PreprocessorPragmaStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorWarning</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorWarning([NotNull] GamaPreprocessorParser.PreprocessorWarningContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorWarning</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorWarning([NotNull] GamaPreprocessorParser.PreprocessorWarningContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PreprocessorError</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessorError([NotNull] GamaPreprocessorParser.PreprocessorErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PreprocessorError</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessorError([NotNull] GamaPreprocessorParser.PreprocessorErrorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preInclude"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreInclude([NotNull] GamaPreprocessorParser.PreIncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preInclude"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreInclude([NotNull] GamaPreprocessorParser.PreIncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.symbolList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbolList([NotNull] GamaPreprocessorParser.SymbolListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.symbolList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbolList([NotNull] GamaPreprocessorParser.SymbolListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreDefineBool</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreDefineBool([NotNull] GamaPreprocessorParser.StmtPreDefineBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreDefineBool</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreDefineBool([NotNull] GamaPreprocessorParser.StmtPreDefineBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreDefineAbsolute</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreDefineAbsolute([NotNull] GamaPreprocessorParser.StmtPreDefineAbsoluteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreDefineAbsolute</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreDefineAbsolute([NotNull] GamaPreprocessorParser.StmtPreDefineAbsoluteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreDefineMacro</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreDefineMacro([NotNull] GamaPreprocessorParser.StmtPreDefineMacroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreDefineMacro</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreDefineMacro([NotNull] GamaPreprocessorParser.StmtPreDefineMacroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreSet([NotNull] GamaPreprocessorParser.PreSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreSet([NotNull] GamaPreprocessorParser.PreSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preUndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreUndef([NotNull] GamaPreprocessorParser.PreUndefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preUndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreUndef([NotNull] GamaPreprocessorParser.PreUndefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreIfStringEq</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreIfStringEq([NotNull] GamaPreprocessorParser.StmtPreIfStringEqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreIfStringEq</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreIfStringEq([NotNull] GamaPreprocessorParser.StmtPreIfStringEqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreIfStringNe</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreIfStringNe([NotNull] GamaPreprocessorParser.StmtPreIfStringNeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreIfStringNe</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreIfStringNe([NotNull] GamaPreprocessorParser.StmtPreIfStringNeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StmtPreIfNumericComp</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtPreIfNumericComp([NotNull] GamaPreprocessorParser.StmtPreIfNumericCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StmtPreIfNumericComp</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.preIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtPreIfNumericComp([NotNull] GamaPreprocessorParser.StmtPreIfNumericCompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preIfdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIfdef([NotNull] GamaPreprocessorParser.PreIfdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preIfdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIfdef([NotNull] GamaPreprocessorParser.PreIfdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preIfndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreIfndef([NotNull] GamaPreprocessorParser.PreIfndefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preIfndef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreIfndef([NotNull] GamaPreprocessorParser.PreIfndefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.prePragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrePragma([NotNull] GamaPreprocessorParser.PrePragmaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.prePragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrePragma([NotNull] GamaPreprocessorParser.PrePragmaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preWarning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreWarning([NotNull] GamaPreprocessorParser.PreWarningContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preWarning"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreWarning([NotNull] GamaPreprocessorParser.PreWarningContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GamaPreprocessorParser.preError"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreError([NotNull] GamaPreprocessorParser.PreErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GamaPreprocessorParser.preError"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreError([NotNull] GamaPreprocessorParser.PreErrorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Source</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.src"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSource([NotNull] GamaPreprocessorParser.SourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Source</c>
	/// labeled alternative in <see cref="GamaPreprocessorParser.src"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSource([NotNull] GamaPreprocessorParser.SourceContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
